//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNFeDll.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string iNFeDll_HomologacaoRSnfeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoRSnfeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2." +
            "asmx")]
        public string iNFeDll_HomologacaoSEnfeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoSEnfeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx")]
        public string iNFeDll_ProducaoSEnfeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoSEnfeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx")]
        public string iNFeDll_ProducaoSEnfeRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoSEnfeRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx")]
        public string iNFeDll_ProducaoSECancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["iNFeDll_ProducaoSECancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string iNFeDll_ProducaoSEinutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoSEinutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string iNFeDll_ProducaoSEconsulta_NfeConsulta2 {
            get {
                return ((string)(this["iNFeDll_ProducaoSEconsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string iNFeDll_ProducaoSEstatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["iNFeDll_ProducaoSEstatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeCancelamento/NfeCancelamento" +
            "2.asmx")]
        public string iNFeDll_HomologacaoSEcancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoSEcancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao" +
            "2.asmx")]
        public string iNFeDll_HomologacaoSEinutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoSEinutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string iNFeDll_HomologacaoSEconsulta_NfeConsulta2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoSEconsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServi" +
            "co2.asmx")]
        public string iNFeDll_HomologacaoSEstatusservico_NfeStatusServico2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoSEstatusservico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string iNFeDll_HomologacaoPArecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoPArecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string iNFeDll_HomologacaoPAretRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoPAretRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string iNFeDll_ProducaoPArecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoPArecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeRetRecepcao2/NFeRetRecepcao2.asmx")]
        public string iNFeDll_ProducaoPAretRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoPAretRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeRecepcao2.asmx")]
        public string iNFeDll_HomologacaoBArecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBArecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeRetRecepcao2.asmx")]
        public string iNFeDll_HomologacaoBAretRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBAretRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeCancelamento2.asmx")]
        public string iNFeDll_HomologacaoBACancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBACancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeInutilizacao2.asmx")]
        public string iNFeDll_HomologacaoBAInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBAInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeConsulta2.asmx")]
        public string iNFeDll_HomologacaoBAConsulta_NfeConsulta2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBAConsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeStatusServico2.asmx")]
        public string iNFeDll_HomologacaoBAStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBAStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx")]
        public string iNFeDll_HomologacaoBACadConsulta_CadConsultaCadastro2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoBACadConsulta_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeRecepcao2.asmx")]
        public string iNFeDll_ProducaoBANfeRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoBANfeRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeRetRecepcao2.asmx")]
        public string iNFeDll_ProducaoBAretRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoBAretRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeCancelamento2.asmx")]
        public string iNFeDll_ProducaoBAcancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["iNFeDll_ProducaoBAcancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeInutilizacao2.asmx")]
        public string iNFeDll_ProdutoBAinutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["iNFeDll_ProdutoBAinutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeConsulta2.asmx")]
        public string iNFeDll_ProdutoBAconsulta_NfeConsulta2 {
            get {
                return ((string)(this["iNFeDll_ProdutoBAconsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeStatusServico2.asmx")]
        public string iNFeDll_ProducaoBAstatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["iNFeDll_ProducaoBAstatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx")]
        public string iNFeDll_ProducaoBAcadConsulta_CadConsultaCadastro2 {
            get {
                return ((string)(this["iNFeDll_ProducaoBAcadConsulta_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string iNFeDll_HomologacaoPAcancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoPAcancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string iNFeDll_HomologacaoPAinutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoPAinutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string iNFeDll_HomologacaoPAconsulta_NfeConsulta2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoPAconsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string iNFeDll_HomologacaoPAstatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["iNFeDll_HomologacaoPAstatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeCancelamento2/NFeCancelamento2.asmx")]
        public string iNFeDll_ProducaoPAcancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["iNFeDll_ProducaoPAcancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeInutilizacao2/NFeInutilizacao2.asmx")]
        public string iNFeDll_ProducaoPAinutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["iNFeDll_ProducaoPAinutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/nfeconsulta2/nfeconsulta2.asmx")]
        public string iNFeDll_ProducaoPAconsulta_NfeConsulta2 {
            get {
                return ((string)(this["iNFeDll_ProducaoPAconsulta_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeStatusServico2/NFeStatusServico2.asmx")]
        public string iNFeDll_ProducaoPAstatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["iNFeDll_ProducaoPAstatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string iNFeDll_br_gov_fazenda_sefazvirtual_www_RecepcaoEvento {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_sefazvirtual_www_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nfe.fazenda.gov.br/NFeConsultaDest/NFeConsultaDest.asmx")]
        public string iNFeDll_br_gov_fazenda_nfe_www_NFeConsultaDest {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_nfe_www_NFeConsultaDest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string iNFeDll_br_gov_fazenda_nfe_recepcaoevento_an_RecepcaoEvento {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_nfe_recepcaoevento_an_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.nfe.fazenda.gov.br/NfeDownloadNF/NfeDownloadNF.asmx")]
        public string iNFeDll_br_gov_fazenda_nfe_www_download_NfeDownloadNF {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_nfe_www_download_NfeDownloadNF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string iNFeDll_br_gov_fazenda_sefazvirtual_www1_NfeAutorizacao {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_sefazvirtual_www1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string iNFeDll_br_gov_fazenda_sefazvirtual_NfeRetAut310_NfeRetAutorizacao {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_sefazvirtual_NfeRetAut310_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx")]
        public string iNFeDll_br_gov_fazenda_sefazvirtual_www1_NFeAutorizacao4 {
            get {
                return ((string)(this["iNFeDll_br_gov_fazenda_sefazvirtual_www1_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx")]
        public string iNFeDll_NfeAutorizacao4_svan_NFeAutorizacao4 {
            get {
                return ((string)(this["iNFeDll_NfeAutorizacao4_svan_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asm" +
            "x")]
        public string iNFeDll_NFeRecepcaoEvento4_svan_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["iNFeDll_NFeRecepcaoEvento4_svan_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefazvirtual.fazenda.gov.br/NFeRetAutorizacao4/NFeRetAutorizacao4.asm" +
            "x")]
        public string iNFeDll_NFeRetAutorizacao4_svan_NFeRetAutorizacao4 {
            get {
                return ((string)(this["iNFeDll_NFeRetAutorizacao4_svan_NFeRetAutorizacao4"]));
            }
        }
    }
}
